### ISSUE TITLE
Control Scaling Issues

### ISSUE THREAD

**Issue by JThramer** [d0ping/DBMapSelectorViewController#2]
Creating an issue here to mirror complain on CocoaControls. 

Link: https://www.cocoacontrols.com/controls/dbmapselectorviewcontroller#comment-1952376328

Contents: "The control doesn't scale well. Tested on a full screen iPhone 6. The dragable buttons touch area is located at a different place then the actual visual. Please find a solution for this because this could be a great plugin if this error is fixed!"

![Bug Photo](https://a.disquscdn.com/uploads/mediaembed/images/1920/7746/original.jpg?w=600&h)

**Comment by d0ping** [comment]
I think I know what's wrong. I try to fix it in the near future.
Thank for the feedback.

**Comment by d0ping** [comment]
This bug was fixed on 1.2.0 version
