### ISSUE TITLE
Circle resizing issue

### ISSUE THREAD

**Issue by asefnoor** [d0ping/DBMapSelectorViewController#4]
It is coming along nicely overall but when I try to increase circle radius, it does not increase. Then I zoom in map and try to increase circle radius, it increases radius circle.

**Comment by d0ping** [comment]
I don't understand how you execute to increasing circle radius. Could you tell us more? Maybe just the radius point is too small and you didn't disturb it?

**Comment by asefnoor** [comment]
I just did following 

self.mapSelectorManager.circleCoordinate = CLLocationCoordinate2DMake(self.centerCoordinate.latitude, self.centerCoordinate.longitude);
    self.mapSelectorManager.circleRadiusMin = 10;
    self.mapSelectorManager.circleRadius = 3000;
    self.mapSelectorManager.circleRadiusMax = 100000;
    [self.mapSelectorManager applySelectorSettings];

It zoom in map and draw a circle on map. I would have agreed with raidus point too small but sometimes it increases radius and sometimes it does not. Let me attach picture as well.

**Comment by asefnoor** [comment]
Hey,

I changed line following 
region.span = MKCoordinateSpanMake(selectorRegion.span.latitudeDelta *2.0f, selectorRegion.span.longitudeDelta *2.0f);
from 
region.span = MKCoordinateSpanMake(selectorRegion.span.latitudeDelta *1.5f, selectorRegion.span.longitudeDelta *1.5f);

Now it is working nicely.

**Comment by d0ping** [comment]
Do I understand correctly that this error is no longer relevant?  Can I close this issue?

**Comment by asefnoor** [comment]
Yes please close it.

**Comment by d0ping** [comment]
Thanks!
