### ISSUE TITLE
UILongPressGestureRecognizer для перемещения радиуса

### ISSUE THREAD

**Issue by staticdreams** [d0ping/DBMapSelectorViewController#6]
Денис, привет. Отличный компонент!

Слушай, я столкнулся с некоторой проблемой. Кроме нарисованного круга и зеленого маркера у меня у меня еще много других маркеров на карте и, порой, твой зеленый очень сложно выловить пальцем чтоб перетащить в другую часть карты. 

Можно ли добавить опцию `UILongPressGestureRecognizer` к компоненту чтобы долгим нажатием пальца радиус рисовался в другом месте? Это бы очень упростило жизнь тем у кого много других маркеров, а не голая карта.

Я бы и сам попробовал сделать, но я полный пень в obj-c, а твой компонент использую со Swift через Cocoapods. Кстати работает на ура.

Спасибо большое!

**Comment by d0ping** [comment]
Привет, Peter!
Хорошая идея. Добавил возможность задать новое местоположение при долгом нажатии (свойство `BOOL shouldLongPressGesture`). По умолчанию выключено. В ближайшее время обновлю под и можно будет пользоваться.
И спасибо за фидбек по Swift. У самого не дошли руки потестить. ))

**Comment by staticdreams** [comment]
Спасибо! Жду обновления с нетерпением)
