### ISSUE TITLE
Region span padding

### ISSUE THREAD

**Issue by staticdreams** [d0ping/DBMapSelectorViewController#7]
Еще одна маленькая просьба :-)

В `DBMapSelectorManager.m` --> `updateMapRegionForMapSelector()` ты фиксируешь span региона на который "наезжает" камера на `2.f`. Можно ли это значение тоже выделить в отдельную переменную? Например я изменил ее на 1.2f (чтоб поближе можно было смотреть что попадет в радиус)

![ios simulator screen shot 30 jun 2015 12 14 14](https://cloud.githubusercontent.com/assets/988705/8428812/fd97997c-1f21-11e5-9be0-8d725e88fbd8.png)

**Comment by d0ping** [comment]
Вынес в отдельную переменную `CGFloat mapRegionCoef`. Обновлю под в ближайшее время.

**Comment by d0ping** [comment]
Обновил под. Теперь можно использовать.

**Comment by staticdreams** [comment]
Спасибо за такую оперативность, Денис!
